[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap = "7gaRU4K2ACK6YGg5aBxehW1y9Q6LHKUaryYiPWfpj5Ju"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/himax/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
